### ISSUE TITLE
Logo for citybike-turku-android

### ISSUE THREAD

**Issue by familqasimov** [iffa/citybike-turku-android#1]
Hi sir. I'm graphics designer. I have studied your work. I think a simple logo will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify. Colors were selected as an example. You can write whatever you want.

![bike service](https://user-images.githubusercontent.com/36432269/41637984-e08152b2-7467-11e8-8c65-34a86dad4849.png)

BEST REGARD

**Comment by iffa** [comment]
Hi! Thanks for your contribution, however as of now I do not need a logo for my project. Thanks a lot anyway!
